# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSTBDHslPbZMJ5JOFeKUEQ_UyFucFOT2
"""

from google.colab import files
import pandas as pd
import numpy as np
data_set = pd.read_csv('/content/drive/MyDrive/Wuzzuf_Jobs.csv')

data_set

data_set.describe()

data_set.shape

data_set.info()

data_set.duplicated().sum()

for col in ['Type', 'Level', 'Location', 'YearsExp', 'Country']:
    print(f"\n{col} - Unique Values:")
    print(data_set[col].value_counts())

data_set['YearsExp'].str.extract(r'(\d+)')

import matplotlib.pyplot as plt

skills_series = data_set['Skills'].dropna().str.split(',')
f_skills = []
for skills in skills_series:
    for skill in skills:
        f_skills.append(skill.strip())
skills_counts = pd.Series(f_skills).value_counts().head(10)
plt.figure(figsize=(10,6))
skills_counts.plot(kind='bar', color='skyblue')
plt.title('Top 10 Most Demanded Skills')
plt.xlabel('Skill')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

data_set_skills = data_set[['Level', 'Skills']].dropna()


data_set_skills['Skills'] = data_set_skills['Skills'].str.split(',')

data_set_skills = data_set_skills.explode('Skills')

data_set_skills['Skills'] = data_set_skills['Skills'].str.strip()

top_skills_by_level = (
    data_set_skills.groupby('Level')['Skills']
    .value_counts()
    .groupby(level=0)
    .head(5)
)
print(top_skills_by_level)

top_skills_by_level.unstack().fillna('-')

data_set['MinYearsExp'] = data_set['YearsExp'].str.extract(r'(\d+)').astype(float)
skills_table = data_set[['Title', 'Company', 'Level', 'Skills']].dropna().copy()
skills_table['Skills'] = skills_table['Skills'].str.split(',')
skills_table = skills_table.explode('Skills')
skills_table['Skills'] = skills_table['Skills'].str.strip()
skills_table.reset_index(drop=True, inplace=True)
skills_table['JobID'] = skills_table.index + 1

data_set.to_csv('jobs_main.csv', index=False)
skills_table.to_csv('job_skills.csv', index=False)
files.download('jobs_main.csv')
files.download('job_skills.csv')

import seaborn as sns
data_set['MinYearsExp'] = data_set['YearsExp'].str.extract(r'(\d+)').astype(float)

flat_skills = skills_table['Skills'].dropna().str.strip().tolist()

skills_counts = pd.Series(flat_skills).value_counts().head(10)
plt.figure(figsize=(10,6))
skills_counts.plot(kind='barh', color='skyblue')
plt.title('Top 10 Most In-Demand Skills')
plt.xlabel('Count')
plt.gca().invert_yaxis()
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

skills_by_level = skills_table.groupby(['Level', 'Skills']).size().reset_index(name='Count')
plt.figure(figsize=(12, 6))
top_skills = skills_by_level.groupby('Level').apply(lambda d: d.nlargest(5, 'Count')).reset_index(drop=True)
sns.barplot(data=top_skills, x='Skills', y='Count', hue='Level')
plt.title('Top Skills by Job Level')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
sns.histplot(data_set['MinYearsExp'].dropna(), bins=10, kde=True, color='orange')
plt.title('Distribution of Minimum Required Experience')
plt.xlabel('Minimum Years of Experience')
plt.ylabel('Job Count')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

type_counts = data_set['Type'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.Pastel1.colors)
plt.title('Job Type Distribution')
plt.tight_layout()
plt.show()

top_companies = data_set['Company'].value_counts().head(10)
plt.figure(figsize=(10,6))
top_companies.plot(kind='barh', color='green')
plt.title('Top Hiring Companies')
plt.xlabel('Number of Jobs')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()